repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
  - repo: https://github.com/prettier/prettier
    rev: 2.4.1
    hooks:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: master
    hooks:
      - id: commitizen
        stages: [commit-msg]
